### ISSUE TITLE
Feature request: Be able to restart simulation without reseting the patient data.

### ISSUE THREAD

**Issue by stuthedew** [luktinghin/simtiva#20]
Sometimes I want to restart a simulation for a patient to try a different starting bolus or infusion rate to see how quickly I reach a target. It would be nice to be able to restart the simulation without having to re-enter patient data every time. Basically, keep the same simulation setup but start over at time zero (or even just go back in time partially)

**Comment by luktinghin** [comment]
Hi, thank you for taking the time to comment. 
(1) the first part is easy to achieve. Let me add that in the next update. -> "reset infusion scheme with the same patient". I think I can incorporate this into the "reset" menu button and then add a step for the user to choose whether the user wants to reset and clear patient data , or like you say, reset the infusion but keep patient details intact
(2) go back in time partially -> this is also achievable, but somewhat more difficult, in terms of user interface design. In fact, the data is always there (the PK data and the infusion scheme data from time zero to time 7200s beyond the scheme start time) and the app just creates the illusion of time progressing by "reading" the "current time instance" by looking into the data at "time point X elapsed since time zero". Programmatically it is quite easy to look back (and forward) in time. But the interface I am not so sure. There is a (quite basic and rudimentary) module now , that u can state "X mins ago, the infusion rate was changed to _ and _ mg bolus was given" and then the resultant PK graph will be re-generated based on the retrospective course correction. I shall think about how to implement this better.

**Comment by luktinghin** [comment]
Hi, the latest update of SimTIVA allows resetting the infusion while keeping patient data, pausing of sim, and jumping back and forward in time. 

Thanks for your idea and contribution!

**Comment by stuthedew** [comment]
That’s awesome! Thank you so much!

And also, the helicopter emergency medicine team at my hospital was having some challenges figuring out the best way to transition from inhalational anesthetics to propofol infusion (timing, starting dose, boluses vs no boluses) to get a smoother transition when they would pick up a patient at an outlying hospital direct from their OR on inhalational anesthetic but were transferred back by helicopter on propofol. We used SimTIVA as part of an educational series on the effect of propofol starting dose rate, boluses etc. on time to effective effect site concentration. It was very well received and the main thing they found helpful in getting a more intuitive grasp was SimTIVA. Thanks again!

Stuart
