### ISSUE TITLE
Custom Opioid Concentration (dilution) bug on "Quick Reset"

### ISSUE THREAD

**Issue by David8L** [luktinghin/simtiva#25]
Issue:
When a custom opioid dilution is set (e.g remifentanil), it resets to 20mcg/ml when "Quick Reset" is hit

To replicate:
Create a simulation with a custom remifentanil dilution, run the simulation for a few seconds, then press "Quick Reset", the concentration will change back to 20mcg/ml

Code inspection:
When running a custom opioid concentration, it would appear that document.getElementById("select_remidilution").value is stuck on "20", but drug_sets[0].infusate_concentration is set to the correct custom value.
When "Quick Reset" is pressed, drug_sets[0].infusate_concentration is changed back to "20"

**Comment by luktinghin** [comment]
Dear David,

Thanks for filing this bug report. I have corrected this mistake. The mistake is caused by a data validation script, which resets the custom opioid dilution back to default, but the reset is erroneously applied to all custom opioid dilution values because the statement for the reset fell outside of the brackets of an if-then condition block.

The commit for corrected version is here. https://github.com/luktinghin/simtiva/commit/cb941acd04cc23e45ec6d31684a7570151599636

Thank you once again.

Yours sincerely,
Terence

**Comment by David8L** [comment]
Thanks for the quick fix. Great work.
Those tricky brackets - I looked at that part of the code, and didn't pick it up. Thanks.

**Comment by luktinghin** [comment]
Thank you once again!
Have a nice day

**Comment by David8L** [comment]
Don't want to raise another issue, but the current custom dilution script allows blank values, or even text values. If you select "custom" then just press OK without entering a value, the code will run with a blank custom value.
Current code is:
if (temp > 100 || temp < 0.1) {

Suggest change to:
if (!(temp > 0.1 && temp < 100)) {

What do you think?

**Comment by luktinghin** [comment]
Dear David,

Thank you for your feedback. This is very important for continuous
improvement.

I have thought about the process of receiving input for the opioid dilution
popup box. I think the better approach for validating user input at this
point would be, to display an error prompt in the same popup box (where the
user sets the custom opioid dilution value), and to prevent errors in
entering wrong custom dilution value into the system. This way, the user
would be prevented from entering wrong values into the system. (Screenshot
attached)

I have therefore written "popup_dilution_validate" function, which serves
this purpose. After this update, the user would not be allowed to enter
wrong values into the system. The validation is performed at the moment the
user clicks "ok" on the custom dilution popup. If the validation shows that
the value is erroneous, the opioid dilution will be reset to default, and
an error prompt shown (in the existing popup window), and the user needs to
enter a correct value before proceeding again. The user can also click "X"
on top right corner to close this popup box if he so wishes to discontinue
the opioid customization.

I think this is the ideal way to validate this process. Because the "master
data entry on the first screen" is one popup already (bottom layer), and
the "custom opioid dilution popup" is another popup over the existing layer
(top layer), any prompt from simtiva to user can only be displayed on the
top layer popup, which is the custom opioid dilution popup.

A minor point regarding your email, is that, I think the user cannot enter
non-numerical values in the custom opioid dilution entry field, because the
HTML element has "type=number" in it, in major browsers, theoretically only
numerical input is allowed.

When I first designed simtiva, I didn't think very carefully about
validating user input. Now that simtiva is getting more functions and
getting more complex, these validation and prompts to the user become also
more complex and also more important.

Yours sincerely,
Terence
